name: Maven Install on Push

on:
  push:
    branches:
      - 'main'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11  
        uses: actions/setup-java@v4 
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Maven Install
        run: ./mvnw install
